default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: fire_sale_development

test:
  <<: *default
  database: fire_sale_test

production:
  <<: *default
  database: fire_sale_production
  username: fire_sale
  password: <%= ENV['FIRE_SALE_DATABASE_PASSWORD'] %>
